export const APP_CONFIG = Symbol("APP_CONFIG");
export const APP_LOGGER = Symbol("APP_LOGGER");
export const APP_LOCALE = Symbol("APP_LOCALE");
export const FETCH_IMPL = Symbol("FETCH_IMPL");
export const AUTH_MANAGER = Symbol("AUTH_MANAGER");
export const SPOTIFY_CLIENT = Symbol("SPOTIFY_CLIENT");
export const PRISMA_CLIENT = Symbol("PRISMA_CLIENT");
export const DATABASE_FEATURES = Symbol("DATABASE_FEATURES");
export const ARCHIVE_REPOSITORY = Symbol("ARCHIVE_REPOSITORY");
export const APP_STATE_REPOSITORY = Symbol("APP_STATE_REPOSITORY");
export const HISTORY_REPOSITORY = Symbol("HISTORY_REPOSITORY");
export const CONSOLE_NOTIFIER = Symbol("CONSOLE_NOTIFIER");
export const TRACK_WATCHER = Symbol("TRACK_WATCHER");
export const AUTO_PLAYLISTS_FREQUENT_SYNC_SERVICE = Symbol("AUTO_PLAYLISTS_FREQUENT_SYNC_SERVICE");
export const AUTO_PLAYLISTS_RARE_SYNC_SERVICE = Symbol("AUTO_PLAYLISTS_RARE_SYNC_SERVICE");
export const AUTO_PLAYLISTS_MERGED_SYNC_SERVICE = Symbol("AUTO_PLAYLISTS_MERGED_SYNC_SERVICE");
export const AUTO_PLAYLISTS_PLAYLIST_RECENT_SYNC_SERVICE = Symbol(
  "AUTO_PLAYLISTS_PLAYLIST_RECENT_SYNC_SERVICE",
);
export const AUTO_PLAYLISTS_SYNC_RUNNER = Symbol("AUTO_PLAYLISTS_SYNC_RUNNER");
